name: "Install Solidity Compiler"

runs:
  using: "composite"
  steps:
    - name: Put Solc Direcotry into PATH
      shell: bash
      run: |
        mkdir -p solc
        echo "$(pwd)/solc/" >> $GITHUB_PATH

    - name: Figure out Solc Download URL
      shell: bash
      run: |
        if [[ "${{ runner.os }}" == "Linux" ]]; then
          echo "SOLC_NAME=solc-static-linux" >> $GITHUB_ENV
        elif [[ "${{ runner.os }}" == "Windows" ]]; then
          echo "SOLC_NAME=solc-windows.exe" >> $GITHUB_ENV
        else
          echo "SOLC_NAME=solc-macos" >> $GITHUB_ENV
        fi

    - name: Download Solc
      shell: bash
      run: |
        curl -sSL --output solc/solc https://github.com/ethereum/solidity/releases/download/v0.8.28/${SOLC_NAME}

    - name: Make Solc Executable
      shell: bash
      run: |
        chmod +x solc/solc
