//! Barrett specialization of 256-bit unsigned division and remainder by
//! compile-time constants, and of `__mulmod` calls with compile-time moduli.
//!
//! A Barrett reduction replaces a runtime division by a constant `C` with a
//! multiplication by the precomputed reciprocal `floor(2^k / C)` followed by
//! a shift and at most a bounded number of conditional corrections — no
//! runtime division at all.
//!
//! The div/rem specialization runs as part of [`super::Context::lower_wide_division`],
//! AFTER the full LLVM optimization pipeline, for two reasons:
//!
//! - Constants are fully exposed there: IPSCCP and inlining have already
//!   propagated compile-time divisors across function boundaries, so one
//!   late sweep sees every eligible site.
//! - Helpers generated here are never touched by the pipeline again, so they
//!   can never be calling-convention-promoted (e.g. to `fastcc`) between
//!   creation and use. If, for instance, a helper were to be reused across
//!   optimization phases, `x % C` could be compiled into a silent trap
//!   through exactly that promotion. Creating helpers post-pipeline makes
//!   that failure mode structurally impossible.
//!
//! The `__mulmod` specialization instead runs primarily BEFORE the pipeline
//! (from [`super::Context::specialize_constant_modulus_mulmod`], behind a
//! small constant-folding pre-pass): waiting until after the pipeline loses
//! the common single-constant-modulus contract, where the inliner dissolves
//! `__mulmod`'s body into callers and no rewritable call site survives.
//! [`super::Context::lower_wide_division`] repeats the sweep post-pipeline
//! for moduli that only become constant during optimization. Running early
//! is safe because the rewrite targets the pre-existing EXTERNAL
//! `__mulmod_barrett`, which the pipeline can neither
//! calling-convention-promote nor argument-strip; the helper-reuse trap
//! above concerns internal helpers generated by the compiler.

use inkwell::values::InstructionOpcode;
use num::{BigUint, One, Zero};

use crate::polkavm::context::{attribute::Attribute, Context};

/// Reserved name prefix shared by every generated Barrett helper function.
/// [`super::Context::lower_wide_division`] skips functions carrying this
/// prefix when walking the module, so freshly generated helper bodies are
/// never themselves candidates for rewriting.
pub const HELPER_PREFIX: &str = "__barrett_";

/// Operation infix of the generated unsigned division helpers: their names
/// are [`HELPER_PREFIX`] + this + the divisor in lowercase hexadecimal
/// (no leading zeros, so at most 64 digits for an i256 divisor —
/// deterministic and bounded).
pub const UDIV_HELPER_INFIX: &str = "udiv_256_";

/// Operation infix of the generated unsigned remainder helpers: their names
/// are [`HELPER_PREFIX`] + this + the divisor in lowercase hexadecimal
/// (no leading zeros, so at most 64 digits for an i256 divisor —
/// deterministic and bounded).
pub const UREM_HELPER_INFIX: &str = "urem_256_";

/// The number of bits in one LLVM `ConstantInt` limb.
const LIMB_BITS: u32 = 64;

/// How an eligible `__mulmod` call site with a compile-time constant modulus
/// is rewritten.
#[derive(Debug)]
pub enum MulModRewrite {
    /// The modulus is a non-power-of-two 256-bit constant: the call is
    /// redirected to `__mulmod_barrett`, with the low word of the Barrett
    /// reciprocal `floor(2^512 / m) - 2^256` supplied as the fourth argument.
    BarrettCall(BigUint),
    /// The modulus is an exact power of two `2^k` with `k` in `0..=255`
    /// (including the `mu_lo`-overflow case `2^255` and the `m = 1` case):
    /// the call is replaced inline by `mul` + `and` with the mask `2^k - 1`.
    /// Proof: `a*b ≡ (a*b mod 2^256) (mod 2^k)` since `2^k | 2^256`; `k = 0`
    /// gives mask `0 -> 0`, correct mod 1. Two instructions, no helper.
    PowerOfTwoMask(u32),
}

impl<'ctx> Context<'ctx> {
    /// Returns the divisor of an i256 `udiv`/`urem` instruction if it is a
    /// compile-time constant eligible for Barrett specialization.
    ///
    /// Eligible means `1 < C < 2^256` and `C` not a power of two. Divisors of
    /// 0, 1, and `2^k` are LLVM folding territory: instcombine canonicalizes
    /// power-of-two div/rem to shifts at O1+ so such sites normally never
    /// reach this pass, but `default<O0>` runs no instcombine, making the
    /// exclusion mandatory rather than hygiene. Excluded sites fall through
    /// to the runtime routing, which is correct at any optimization level.
    /// A constant dividend with a runtime divisor also stays routed.
    pub(crate) fn barrett_eligible_divisor(
        builder: &inkwell::builder::Builder<'ctx>,
        instruction: &inkwell::values::InstructionValue<'ctx>,
    ) -> Option<BigUint> {
        if !matches!(
            instruction.get_opcode(),
            InstructionOpcode::UDiv | InstructionOpcode::URem
        ) {
            return None;
        }
        if !instruction.get_type().is_int_type() {
            return None;
        }
        let divisor = instruction.get_operand(1)?.value()?;
        if !divisor.is_int_value() {
            return None;
        }
        let divisor = divisor.into_int_value();
        if !divisor.is_const() {
            return None;
        }
        builder.position_before(instruction);
        let divisor = Self::wide_unsigned_constant(builder, divisor)?;
        if divisor <= BigUint::one() || divisor.count_ones() == 1 {
            return None;
        }
        Some(divisor)
    }

    /// Classifies a call instruction as an eligible constant-modulus
    /// `__mulmod` rewrite, or `None` to leave the site untouched.
    ///
    /// The callee is compared by pointer identity against the `__mulmod`
    /// function value (`mulmod_callee`), never by name: post-Oz calls to the
    /// private `__mulmod` may carry `fastcc`, and pointer identity is immune
    /// to calling-convention, tail-call, and direct-vs-indirect form. A
    /// hypothetically cloned or specialized `__mulmod` would be missed, which
    /// fails safe (a missed optimization, never wrong code).
    ///
    /// Moduli with fewer than 256 bits (and runtime moduli) stay on
    /// `__mulmod`: `a*b <= (2^256-1)^2 < 2^512` is exactly the HAC 14.42
    /// operand bound at `t = 256`, so only 256-bit moduli admit the shared
    /// helper without pre-reducing the multiplicands.
    pub(crate) fn mulmod_rewrite(
        builder: &inkwell::builder::Builder<'ctx>,
        instruction: &inkwell::values::InstructionValue<'ctx>,
        mulmod_callee: inkwell::values::PointerValue<'ctx>,
    ) -> Option<MulModRewrite> {
        if instruction.get_opcode() != InstructionOpcode::Call {
            return None;
        }
        // Three arguments plus the callee, which LLVM stores last.
        if instruction.get_num_operands() != 4 {
            return None;
        }
        let callee = instruction.get_operand(3)?.value()?;
        if !callee.is_pointer_value() || callee.into_pointer_value() != mulmod_callee {
            return None;
        }
        let modulus = instruction.get_operand(2)?.value()?;
        if !modulus.is_int_value() {
            return None;
        }
        let modulus = modulus.into_int_value();
        if !modulus.is_const() {
            return None;
        }
        builder.position_before(instruction);
        let modulus = Self::wide_unsigned_constant(builder, modulus)?;
        if modulus.count_ones() == 1 {
            return Some(MulModRewrite::PowerOfTwoMask(modulus.bits() as u32 - 1));
        }
        if modulus.bits() == 256 {
            return Some(MulModRewrite::BarrettCall(Self::mulmod_reciprocal_low(
                &modulus,
            )));
        }
        None
    }

    /// Computes the Barrett reciprocal `mu = floor(2^256 / C)` for a division
    /// helper.
    ///
    /// `C` not a power of two implies `2^256 = mu*C + e` with `1 <= e <= C-1`.
    /// The self-check aborts compilation on violation: a compiler bug here
    /// must never become a wrong on-chain result.
    pub(crate) fn division_reciprocal(divisor: &BigUint) -> BigUint {
        let two_pow_256 = BigUint::one() << 256u32;
        let reciprocal = &two_pow_256 / divisor;
        assert!(
            &reciprocal * divisor <= two_pow_256 && (&reciprocal + 1u32) * divisor > two_pow_256,
            "Barrett reciprocal self-check failed for divisor 0x{}",
            divisor.to_str_radix(16),
        );
        reciprocal
    }

    /// Computes the low word `mu_lo = floor(2^512 / m) - 2^256` of the Barrett
    /// reciprocal for an eligible `__mulmod` modulus.
    ///
    /// Range proof: for `2^255 < m <= 2^256 - 1` and `m` not a power of two,
    /// `mu >= 2^256 + 1` (since `(2^256-1)(2^256+1) < 2^512`) and
    /// `mu < 2^257`, so `mu_lo` lies in `[1, 2^256 - 1]`: it always fits an
    /// i256 and is never zero. The self-checks abort compilation on
    /// violation.
    pub(crate) fn mulmod_reciprocal_low(modulus: &BigUint) -> BigUint {
        let two_pow_256 = BigUint::one() << 256u32;
        let two_pow_512 = BigUint::one() << 512u32;
        let reciprocal = &two_pow_512 / modulus;
        assert!(
            &reciprocal * modulus <= two_pow_512 && (&reciprocal + 1u32) * modulus > two_pow_512,
            "Barrett mulmod reciprocal self-check failed for modulus 0x{}",
            modulus.to_str_radix(16),
        );
        assert!(
            reciprocal > two_pow_256,
            "Barrett mulmod reciprocal 0x{} out of range for modulus 0x{}",
            reciprocal.to_str_radix(16),
            modulus.to_str_radix(16),
        );
        let reciprocal_low = reciprocal - two_pow_256;
        assert!(
            reciprocal_low.bits() <= 256,
            "Barrett mulmod reciprocal low word overflows i256 for modulus 0x{}",
            modulus.to_str_radix(16),
        );
        reciprocal_low
    }

    /// Reads an arbitrary-width LLVM unsigned integer constant into a
    /// [`BigUint`] without printing IR.
    ///
    /// For each 64-bit limb the builder is asked for `lshr` on two constant
    /// operands, which LLVM's `IRBuilder` constant folder folds to a plain
    /// constant without inserting an instruction (the builder must merely be
    /// positioned); the limb is then read via `const_truncate` to i64 and
    /// `get_zero_extended_constant`.
    ///
    /// Defensive contract: if a shift result is somehow non-constant, the
    /// accidental instruction is erased and `None` is returned — the call
    /// site falls back to the runtime routing; this function never
    /// miscompiles. The final self-check reconstructs the constant with
    /// [`Self::biguint_constant`] and compares interned pointers (LLVM
    /// interns `ConstantInt`s per context and type, so equality is complete);
    /// this also rejects constant expressions that fold limb-wise but are not
    /// plain `ConstantInt`s.
    pub(crate) fn wide_unsigned_constant(
        builder: &inkwell::builder::Builder<'ctx>,
        value: inkwell::values::IntValue<'ctx>,
    ) -> Option<BigUint> {
        let value_type = value.get_type();
        let i64_type = value_type.get_context().i64_type();
        let limb_count = value_type.get_bit_width().div_ceil(LIMB_BITS);

        let mut result = BigUint::zero();
        for limb_index in (0..limb_count).rev() {
            let shift_amount = value_type.const_int((limb_index * LIMB_BITS) as u64, false);
            let shifted = builder
                .build_right_shift(value, shift_amount, false, "")
                .ok()?;
            if let Some(accidental_instruction) = shifted.as_instruction() {
                accidental_instruction.erase_from_basic_block();
                return None;
            }
            let limb = shifted
                .const_truncate(i64_type)
                .get_zero_extended_constant()?;
            result = (result << LIMB_BITS) | BigUint::from(limb);
        }

        let reconstructed = Self::biguint_constant(value_type, &result);
        if reconstructed != value {
            return None;
        }
        Some(result)
    }

    /// Materializes a [`BigUint`] as an LLVM constant of the given integer
    /// type.
    ///
    /// # Panics
    /// If the value does not fit the type.
    pub(crate) fn biguint_constant(
        int_type: inkwell::types::IntType<'ctx>,
        value: &BigUint,
    ) -> inkwell::values::IntValue<'ctx> {
        let limb_count = int_type.get_bit_width().div_ceil(LIMB_BITS) as usize;
        let mut limbs = value.to_u64_digits();
        assert!(
            limbs.len() <= limb_count && value.bits() <= int_type.get_bit_width() as u64,
            "constant 0x{} does not fit i{}",
            value.to_str_radix(16),
            int_type.get_bit_width(),
        );
        limbs.resize(limb_count, 0);
        int_type.const_int_arbitrary_precision(&limbs)
    }

    /// Returns the Barrett helper function for the given operation and
    /// divisor, generating it on first use.
    ///
    /// The helper has internal linkage, `noinline` and `nounwind`, a single
    /// entry block, and is built with a dedicated builder so the caller's
    /// builder position is never clobbered. Shape (`<wide>` is
    /// `256 + bits(mu)` rounded up to a multiple of 64 — no-wrap proof:
    /// `x*mu < 2^256 * 2^bits(mu) <= 2^wide`; range 320 for large `C` to 512
    /// for `C = 3`):
    ///
    /// ```llvm
    /// define internal i256 @__barrett_udiv_256_<hex>(i256 %x) {
    /// entry:
    ///   %xw = zext i256 %x to i<wide>
    ///   %p  = mul i<wide> %xw, <mu>          ; no wrap (see width proof)
    ///   %s  = lshr i<wide> %p, 256
    ///   %qh = trunc i<wide> %s to i256       ; qh <= q < 2^256: lossless
    ///   %qc = mul i256 %qh, <C>              ; qh*C <= q*C <= x: no wrap
    ///   %r0 = sub i256 %x, %qc               ; r0 in [0, 2C)
    ///   %f  = icmp uge i256 %r0, <C>         ; fires iff qh = q-1
    ///   ; udiv: %q1 = add i256 %qh, 1 ; %q = select %f, %q1, %qh ; ret %q
    ///   ; urem: %r1 = sub i256 %r0, <C> ; %r = select %f, %r1, %r0 ; ret %r
    /// }
    /// ```
    ///
    /// Exactly ONE correction. Proof: with `mu = (2^256 - e)/C`,
    /// `1 <= e <= C-1`, and `qh = floor(x*mu/2^256)`: upper —
    /// `x*mu/2^256 <= x/C` so `qh <= q`; lower —
    /// `x*mu/2^256 = x/C - x*e/(C*2^256)` and `x*e/(C*2^256) < e/C < 1`, so
    /// `qh >= q-1`. Hence `qh` is in `{q-1, q}`, `r0` is in `[0, 2C)`, one
    /// conditional subtract/increment is necessary and sufficient, and
    /// `r0 >= C` iff `qh = q-1`. Tightness: `C = 3` or `5` with
    /// `x = 2^256-1` drives `qh = q-1`, so the correction is not dead code.
    /// A second correction would be provably dead and is deliberately not
    /// emitted (dead margin is untestable code; the emission-time `mu`
    /// self-check guards the only way the premise could break). Do not
    /// harmonize with `__mulmod_barrett`'s two corrections; these are
    /// different theorems.
    ///
    /// Degenerate case `bits(C) == 256` (`mu = 1`): a compare-and-subtract
    /// body is emitted instead — `x < 2^256 < 2C` forces `q` in `{0, 1}`, so
    /// `q = zext(icmp uge x, C)` and `r = select(uge, x - C, x)`. Same helper
    /// name and type; call sites are agnostic to which body was chosen.
    ///
    /// # Panics
    /// If a function with the helper's reserved name exists with a different
    /// type: the prefix is reserved, so a mismatch is a compiler invariant
    /// violation.
    pub(crate) fn barrett_divrem_helper(
        &self,
        opcode: InstructionOpcode,
        divisor: &BigUint,
    ) -> inkwell::values::FunctionValue<'ctx> {
        let operation_infix = match opcode {
            InstructionOpcode::UDiv => UDIV_HELPER_INFIX,
            InstructionOpcode::URem => UREM_HELPER_INFIX,
            _ => unreachable!("only udiv/urem sites are Barrett-specialized"),
        };
        let name = format!(
            "{}{}{}",
            HELPER_PREFIX,
            operation_infix,
            divisor.to_str_radix(16)
        );

        let word_type = self.word_type();
        let helper_type = word_type.fn_type(&[word_type.into()], false);
        if let Some(function) = self.module().get_function(&name) {
            assert!(
                function.get_type() == helper_type,
                "the reserved Barrett helper symbol `{name}` has a mismatched type",
            );
            return function;
        }

        let function = self.module().add_function(
            &name,
            helper_type,
            Some(inkwell::module::Linkage::Internal),
        );
        for attribute in [Attribute::NoInline, Attribute::NoUnwind] {
            function.add_attribute(
                inkwell::attributes::AttributeLoc::Function,
                self.llvm.create_enum_attribute(attribute as u32, 0),
            );
        }

        let builder = self.llvm.create_builder();
        builder.position_at_end(self.llvm.append_basic_block(function, "entry"));
        let dividend = function
            .get_first_param()
            .expect("the Barrett helper takes the dividend")
            .into_int_value();
        let divisor_constant = Self::biguint_constant(word_type, divisor);

        if divisor.bits() as u32 == word_type.get_bit_width() {
            let correction_fires = builder
                .build_int_compare(inkwell::IntPredicate::UGE, dividend, divisor_constant, "")
                .expect("the Barrett helper compare is valid");
            let result = match opcode {
                InstructionOpcode::UDiv => builder
                    .build_int_z_extend(correction_fires, word_type, "")
                    .expect("the Barrett helper zext is valid")
                    .into(),
                InstructionOpcode::URem => {
                    let reduced = builder
                        .build_int_sub(dividend, divisor_constant, "")
                        .expect("the Barrett helper sub is valid");
                    builder
                        .build_select(correction_fires, reduced, dividend, "")
                        .expect("the Barrett helper select is valid")
                }
                _ => unreachable!("only udiv/urem sites are Barrett-specialized"),
            };
            builder
                .build_return(Some(&result))
                .expect("the Barrett helper return is valid");
            return function;
        }

        let reciprocal = Self::division_reciprocal(divisor);
        let wide_width = (word_type.get_bit_width() as u64 + reciprocal.bits())
            .div_ceil(LIMB_BITS as u64) as u32
            * LIMB_BITS;
        let wide_type = self
            .llvm
            .custom_width_int_type(
                std::num::NonZeroU32::new(wide_width).expect("the wide width is non-zero"),
            )
            .expect("the wide width is a valid integer width");

        let dividend_wide = builder
            .build_int_z_extend(dividend, wide_type, "")
            .expect("the Barrett helper zext is valid");
        let product = builder
            .build_int_mul(
                dividend_wide,
                Self::biguint_constant(wide_type, &reciprocal),
                "",
            )
            .expect("the Barrett helper multiply is valid");
        let shifted = builder
            .build_right_shift(
                product,
                wide_type.const_int(word_type.get_bit_width() as u64, false),
                false,
                "",
            )
            .expect("the Barrett helper shift is valid");
        let quotient_estimate = builder
            .build_int_truncate(shifted, word_type, "")
            .expect("the Barrett helper truncate is valid");
        let quotient_times_divisor = builder
            .build_int_mul(quotient_estimate, divisor_constant, "")
            .expect("the Barrett helper multiply is valid");
        let remainder_estimate = builder
            .build_int_sub(dividend, quotient_times_divisor, "")
            .expect("the Barrett helper sub is valid");
        let correction_fires = builder
            .build_int_compare(
                inkwell::IntPredicate::UGE,
                remainder_estimate,
                divisor_constant,
                "",
            )
            .expect("the Barrett helper compare is valid");
        let result = match opcode {
            InstructionOpcode::UDiv => {
                let corrected = builder
                    .build_int_add(quotient_estimate, word_type.const_int(1, false), "")
                    .expect("the Barrett helper add is valid");
                builder
                    .build_select(correction_fires, corrected, quotient_estimate, "")
                    .expect("the Barrett helper select is valid")
            }
            InstructionOpcode::URem => {
                let corrected = builder
                    .build_int_sub(remainder_estimate, divisor_constant, "")
                    .expect("the Barrett helper sub is valid");
                builder
                    .build_select(correction_fires, corrected, remainder_estimate, "")
                    .expect("the Barrett helper select is valid")
            }
            _ => unreachable!("only udiv/urem sites are Barrett-specialized"),
        };
        builder
            .build_return(Some(&result))
            .expect("the Barrett helper return is valid");
        function
    }
}
