name: Hardhat Integration

on:
  workflow_call:

env:
  # Workflow-internal hardhat envs are prefixed with `CI_` to not conflict with the
  # `HARDHAT_*` namespace, which hardhat itself will interpret for its configuration.
  CI_HARDHAT_PROJECT_ROOT: tooling-projects/hardhat/erc20

jobs:
  use-hardhat:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout revive
        uses: actions/checkout@v4

      - name: Download resolc Binary
        uses: actions/download-artifact@v4
        with:
          name: resolc-x86_64-unknown-linux-musl
          path: resolc-bin

      - name: Export resolc path
        run: |
          chmod +x resolc-bin/resolc-x86_64-unknown-linux-musl
          # This env is used by `hardhat.config.js`.
          echo "RESOLC_PATH=$(pwd)/resolc-bin/resolc-x86_64-unknown-linux-musl" >> $GITHUB_ENV

      - name: Set Up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install Project Dependencies
        working-directory: ${{ env.CI_HARDHAT_PROJECT_ROOT }}
        run: npm ci

      - name: Compile Project
        working-directory: ${{ env.CI_HARDHAT_PROJECT_ROOT }}
        run: npx hardhat compile

      - name: Verify Output
        working-directory: ${{ env.CI_HARDHAT_PROJECT_ROOT }}
        run: |
          set -x
          shopt -s nullglob
          build_info_files=(artifacts/build-info/*.json)
          test "${#build_info_files[@]}" -eq 1

          BUILD_INFO="${build_info_files[0]}"
          CONTRACT='.output.contracts["contracts/MyToken.sol"].MyToken'
          SOURCE='.output.sources["contracts/MyToken.sol"]'

          jq -er "$CONTRACT.evm.bytecode.object"          "$BUILD_INFO" | grep -q '^50564d'
          jq -er "$CONTRACT.evm.deployedBytecode.object"  "$BUILD_INFO" | grep -q '^50564d'
          jq -e  "$CONTRACT.evm.methodIdentifiers         | length > 0"  "$BUILD_INFO" > /dev/null
          jq -e  "$CONTRACT.abi                           | length > 0"  "$BUILD_INFO" > /dev/null
          jq -e  "$CONTRACT.storageLayout.storage         | length > 0"  "$BUILD_INFO" > /dev/null
          jq -e  "$CONTRACT.metadata                      | length > 0"  "$BUILD_INFO" > /dev/null
          jq -e  "$SOURCE.ast                             | length > 0"  "$BUILD_INFO" > /dev/null
          jq -e  '.output.sources                         | length > 1'  "$BUILD_INFO" > /dev/null
