name: Reusable Build

on:
  workflow_call:
    inputs:
      is_release:
        description: "Whether this is a release build"
        required: true
        type: boolean
      retention_days:
        description: "Artifact retention days"
        required: false
        type: number
        default: 1
    outputs:
      resolc-x86_64-unknown-linux-musl_url:
        value: ${{ jobs.build-linux.outputs.url }}
      resolc-x86_64-unknown-linux-musl_sha:
        value: ${{ jobs.build-linux.outputs.sha }}
      resolc-aarch64-apple-darwin_url:
        value: ${{ jobs.build-macos.outputs.aarch64-apple-darwin_url }}
      resolc-aarch64-apple-darwin_sha:
        value: ${{ jobs.build-macos.outputs.aarch64-apple-darwin_sha }}
      resolc-x86_64-apple-darwin_url:
        value: ${{ jobs.build-macos.outputs.x86_64-apple-darwin_url }}
      resolc-x86_64-apple-darwin_sha:
        value: ${{ jobs.build-macos.outputs.x86_64-apple-darwin_sha }}
      resolc-universal-apple-darwin_url:
        value: ${{ jobs.build-macos.outputs.universal-apple-darwin_url }}
      resolc-universal-apple-darwin_sha:
        value: ${{ jobs.build-macos.outputs.universal-apple-darwin_sha }}
      resolc-x86_64-pc-windows-msvc_url:
        value: ${{ jobs.build-windows.outputs.url }}
      resolc-x86_64-pc-windows-msvc_sha:
        value: ${{ jobs.build-windows.outputs.sha }}
      resolc-web_js_url:
        value: ${{ jobs.build-wasm.outputs.resolc_web_js_url }}
      resolc-web_js_sha:
        value: ${{ jobs.build-wasm.outputs.resolc_web_js_sha }}

jobs:
  build-linux:
    uses: ./.github/workflows/reusable-build-linux.yml
    with:
      retention_days: ${{ inputs.retention_days }}

  build-macos:
    uses: ./.github/workflows/reusable-build-macos.yml
    with:
      retention_days: ${{ inputs.retention_days }}

  build-windows:
    uses: ./.github/workflows/reusable-build-windows.yml
    with:
      retention_days: ${{ inputs.retention_days }}

  build-wasm:
    uses: ./.github/workflows/reusable-build-wasm.yml
    with:
      is_release: ${{ inputs.is_release }}
      retention_days: ${{ inputs.retention_days }}
