name: Verify Reproducible Builds

on:
  workflow_call:

env:
  # The compiler modes to use for compilation by retester.
  MODES: "Y M0 S+, Y M3 S+, Y Mz S+"
  SOLC_VERSION: "0.8.33"

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      is_release: false
      retention_days: 1

  create-macos-universal:
    needs: build
    runs-on: macos-15
    steps:
      - name: Download MacOS artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: resolc-*-apple-darwin
          merge-multiple: true

      - name: Create MacOS Fat Binary
        run: |
          lipo resolc-aarch64-apple-darwin resolc-x86_64-apple-darwin -create -output resolc-universal-apple-darwin

      - name: Upload Universal Binary
        uses: actions/upload-artifact@v4
        with:
          name: resolc-universal-apple-darwin
          path: resolc-universal-apple-darwin
          retention-days: 1

  compile-and-export-hashes-native:
    needs: [build, create-macos-universal]
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux
            target: x86_64-unknown-linux-musl
            runner: ubuntu-24.04
          - platform: macos
            target: universal-apple-darwin
            runner: macos-15
          - platform: windows
            target: x86_64-pc-windows-msvc
            runner: windows-2022
    runs-on: ${{ matrix.runner }}
    steps:
      # For some deeply nested contracts in `resolc-compiler-tests`, Windows
      # will generate a "Filename too long" error. This step enables long paths.
      - name: Enable Git Long Paths (Windows)
        if: ${{ runner.os == 'Windows' }}
        run: git config --system core.longpaths true

      - name: Checkout revive
        uses: actions/checkout@v4
        with:
          path: revive
          submodules: recursive

      - name: Download Binary
        uses: actions/download-artifact@v4
        with:
          name: resolc-${{ matrix.target }}
          path: resolc-bin

      - name: Make resolc Executable
        shell: bash
        run: chmod +x "resolc-bin/resolc-${{ matrix.target }}${{ runner.os == 'Windows' && '.exe' || '' }}"

      - name: Compile Contracts
        id: compile
        uses: ./revive/revive-differential-tests/.github/actions/compile-contracts
        with:
          revive-differential-tests-path: revive/revive-differential-tests
          resolc-path: resolc-bin/resolc-${{ matrix.target }}${{ runner.os == 'Windows' && '.exe' || '' }}
          solc-version: ${{ env.SOLC_VERSION }}
          modes: ${{ env.MODES }}
          upload-artifact-name: compilation-report-${{ matrix.platform }}

      - name: Export Bytecode Hashes
        uses: ./revive/revive-differential-tests/.github/actions/export-bytecode-hashes
        with:
          revive-differential-tests-path: revive/revive-differential-tests
          report-path: ${{ steps.compile.outputs.report-path }}
          remove-prefix: ${{ steps.compile.outputs.contracts-source-prefix }}
          platform-label: ${{ matrix.platform }}
          upload-artifact-name: hashes-${{ matrix.platform }}

  compare-hashes:
    needs: compile-and-export-hashes-native
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout revive
        uses: actions/checkout@v4
        with:
          path: revive
          submodules: true

      - name: Compare Bytecode Hashes
        uses: ./revive/revive-differential-tests/.github/actions/compare-bytecode-hashes
        with:
          revive-differential-tests-path: revive/revive-differential-tests
          hash-artifact-names: "hashes-linux, hashes-macos, hashes-windows"
          modes: ${{ env.MODES }}
          upload-artifact-name: hash-comparison-result

  run-differential-tests:
    needs: build
    runs-on: parity-large
    timeout-minutes: 90
    env:
      # TODO: Which Polkadot SDK commit do we want to use?
      # The below one is as of March. 25, 2026.
      POLKADOT_SDK_REF: "9d8a2fefd2414591c4a243460f3ffc5195a71deb"
      RUSTFLAGS: "-Awarnings"
    strategy:
      fail-fast: false
      matrix:
        platform: ["revive-dev-node-revm-solc", "revive-dev-node-polkavm-resolc"]
    steps:
      - name: Checkout revive
        uses: actions/checkout@v4
        with:
          path: revive
          submodules: recursive

      - name: Download Binary
        uses: actions/download-artifact@v4
        with:
          name: resolc-x86_64-unknown-linux-musl
          path: ./resolc-bin

      - name: Make resolc Executable
        shell: bash
        run: chmod +x ./resolc-bin/resolc-x86_64-unknown-linux-musl

      - name: Checkout Polkadot SDK
        uses: actions/checkout@v4
        with:
          repository: paritytech/polkadot-sdk
          ref: ${{ env.POLKADOT_SDK_REF }}
          path: polkadot-sdk
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libssl-dev protobuf-compiler llvm clang libclang-dev

      - name: Install forklift
        run: |
          curl -fsSLo forklift https://github.com/paritytech/forklift/releases/download/0.15.0/forklift_0.15.0_linux_amd64
          chmod +x forklift
          sudo mv forklift /usr/local/bin/

      - name: Configure forklift
        run: |
          mkdir -p .forklift
          cp polkadot-sdk/.forklift/config.toml .forklift/config.toml

      - name: Set Up Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: "1.90.0"
          target: "wasm32-unknown-unknown"
          components: "rust-src"
          rustflags: ""

      - name: Run Differential E2E Tests
        uses: ./revive/revive-differential-tests/.github/actions/run-differential-tests
        with:
          revive-differential-tests-path: revive/revive-differential-tests
          polkadot-sdk-path: ./polkadot-sdk
          cargo-command: "forklift cargo"
          platform: ${{ matrix.platform }}
          resolc-path: ./resolc-bin/resolc-x86_64-unknown-linux-musl
          solc-version: ${{ env.SOLC_VERSION }}
          # TODO: Verify that the expected failures in the files are actually expected.
          #       The entries in those files come from the generated expectations file
          #       from this run: https://github.com/paritytech/revive/actions/runs/24132123802/job/70412879350
          expectations-file-path: ./revive/.github/assets/${{ matrix.platform }}.json

  # Sentinel job that depends on the jobs we want to allow completing
  # (instead of being canceled once the other job chains complete).
  # Thus, run-differential-tests will always run even if compare-hashes finishes first.
  wait-for-jobs:
    if: ${{ always() }}
    needs: [compare-hashes, run-differential-tests]
    runs-on: ubuntu-24.04
    steps:
      - run: echo "All jobs finished"
